name: courier_app
description: Courier's app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.7.0
  flutter_secure_storage: ^9.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.3.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.6
  get: ^4.6.6
  intl: ^0.19.0
  #flutter pub run intl_utils:generate
  intl_utils: ^2.8.7
  email_validator: ^3.0.0
  geolocator: ^10.1.0
  flutter_dotenv: ^5.2.1
  restart_app: ^1.3.2
  internet_connection_checker_plus: ^2.5.2
  fast_cached_network_image: ^1.2.9
  action_slider: ^0.7.0
  get_it: ^7.6.4
  injectable: ^2.3.2
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  url_launcher: ^6.3.1
  awesome_notifications: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.6
  firebase_core_platform_interface: ^5.0.0
  flutter_gen_runner: ^5.3.2
# flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
#  surf_lint_rules: ^3.0.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/applogo.png"
flutter_gen:
  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true
  class_name: AppLocale
  main_locale: ru
  arb_dir: lib/res/localization/l10n
  output_dir: lib/res/localization

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - config.env

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900
